# Generated by Django 6.0.5 on 2026-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_active",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя активность"
            ),
        ),
    ]
