# Generated by Django 6.0.5 on 2026-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "😞 Очень плохо"),
                            (2, "😕 Плохо"),
                            (3, "😐 Нормально"),
                            (4, "🙂 Хорошо"),
                            (5, "😊 Отлично"),
                        ],
                        default=3,
                        verbose_name="Настроение",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Запись дневника",
                "verbose_name_plural": "Записи дневника",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Мечта / цель"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В процессе"),
                            ("completed", "Исполнено"),
                            ("postponed", "Отложено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Планируемая дата"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Мечта",
                "verbose_name_plural": "Мечты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название службы"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_24h",
                    models.BooleanField(default=True, verbose_name="Круглосуточно"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Экстренный контакт",
                "verbose_name_plural": "Экстренные контакты",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Привычка")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "target_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Цель (раз в период)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата выполнения"),
                ),
            ],
            options={
                "verbose_name": "Отметка привычки",
                "verbose_name_plural": "Отметки привычек",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_name",
                    models.CharField(max_length=200, verbose_name="Название теста"),
                ),
                ("score", models.IntegerField(verbose_name="Результат (баллы)")),
                (
                    "interpretation",
                    models.TextField(blank=True, verbose_name="Интерпретация"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата прохождения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестов",
                "ordering": ["-created_at"],
            },
        ),
    ]
